Repository baileydunning/rancid-tomatillos, pull requests merged in 2020-12, with the labels that each got.

#6 Feature display movies
  .eslintcache
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Header.js
  src/components/Movie.js
  src/components/RatingForm.js
  src/components/Thumbnail.js
  src/components/ThumbnailContainer.js
  src/css/App.scss
  src/css/Header.scss
  src/css/Movie.scss
  src/css/Thumbnail.scss
  src/css/ThumbnailContainer.scss
  src/logo.svg
  src/movieData.js
Labels: enhancement

#10 Feature/conditional rendering
  .eslintcache
  public/index.html
  src/App.js
  src/components/Header.js
  src/components/Movie.js
  src/components/Thumbnail.js
  src/components/ThumbnailContainer.js
  src/css/App.scss
  src/css/Header.scss
  src/css/Movie.scss
  src/css/Thumbnail.scss
  src/css/ThumbnailContainer.scss
Labels: enhancement

#13 Feature initiate testing
  .eslintcache
  package-lock.json
  package.json
  src/App.test.js
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/Header.test.js
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/Movie/Movie.test.js
  src/Thumbnail-Container/ThumbnailContainer.js
  src/Thumbnail-Container/ThumbnailContainer.scss
  src/Thumbnail-Container/ThumbnailContainer.test.js
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.scss
  src/Thumbnail/Thumbnail.test.js
  src/components/RatingForm.js
  src/index.js
  src/movieData.js
Labels: TDD

#19 Network requests
  .eslintcache
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Movie/Movie.js
  src/Movie/Movie.test.js
  src/Thumbnail/Thumbnail.js
  src/apiCalls.js
  src/setupTests.js
Labels: TDD, enhancement

#21 Refactor/code review
  .eslintcache
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/Header.test.js
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/Search/Search.js
  src/Search/Search.scss
  src/Search/Search.test.js
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.scss
  src/Thumbnail/Thumbnail.test.js
Labels: enhancement

#24 Feature video api
  .eslintcache
  src/App/App.js
  src/App/App.scss
  src/Header/Header.scss
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/Movie/Movie.test.js
  src/Search/Search.js
  src/Thumbnail/Thumbnail.scss
  src/apiCalls.js
Labels: TDD, enhancement

#28 Feature router
  .eslintcache
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Movie/Movie.js
  src/Movie/Movie.test.js
  src/Thumbnail-Container/ThumbnailContainer.test.js
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.test.js
  src/index.js
Labels: enhancement

#35 Create RatingFilter component to filter thumbnails by a range of numbers
  .eslintcache
  src/App/App.js
  src/Rating-Filter/RatingFilter.js
  src/Rating-Filter/RatingFilter.scss
  src/Rating-Filter/RatingFilter.test.js
Labels: enhancement

#37 Test RatingFilter component
  .eslintcache
  src/Rating-Filter/RatingFilter.test.js
Labels: TDD

#38 Refactor/styles
  .eslintcache
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/Header.test.js
  src/Movie/Movie.scss
  src/Rating-Filter/RatingFilter.js
  src/Rating-Filter/RatingFilter.scss
  src/Thumbnail-Container/ThumbnailContainer.scss
  src/Thumbnail/Thumbnail.js
  src/Thumbnail/Thumbnail.scss
  src/Thumbnail/Thumbnail.test.js
  src/Videos/Videos.js
  src/index.js
Labels: enhancement
